# Generated by Django 4.0.1 on 2022-01-16 14:33

import articles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_article_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=articles.models.upload_image_to),
        ),
    ]
